[package]
name = "shadergen"
version = "0.1.0"
edition = "2021"

[dependencies]
lazy_static = "1.5.0"
nom = "8.0.0"
rand = "0.9.0"
egui_inspect = { git = "https://github.com/dmirauta/egui_inspect", branch = "0_31", features = [
  "logging",
] }
egui_extras = "0.31"
