# Color channel
C |  T
  ||| add(C, C)
  ||| mult(C, C)
  ||| mult(C, mult(C,C))
  | sqrt( abs ( C ) )
  # ||| abs(C)
  ||| sin(C)
  ;

# Terminal (should be lower case, otherwise may be confused with replace a rule ident)
T | random
  | u
  | v
  | t
  ;
